# Generated by Django 4.1.6 on 2023-04-05 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todolist_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 6, 32, 2, 796780, tzinfo=datetime.timezone.utc)),
        ),
    ]
