# Generated by Django 4.1.6 on 2023-04-21 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todolist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 21, 7, 34, 18, 215580, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_photo',
            field=models.ImageField(default='profile/empty.webp', upload_to='app/images'),
        ),
    ]
